### ISSUE TITLE
Transition9 is not a dependency on haxelib

### ISSUE THREAD

**Issue by jasononeil** [dionjwa/haxe_remoting#1]
It took me quite a while to figure out that transition9 is needed to make this work.  Would be great if it was included in the haxelib dependencies so it would be installed automatically...

**Comment by dionjwa** [comment]
I'm having a ton of trouble updating the haxelib packages. It's a headache,
I'm not the only one, and no-one has offered any solution. Please be
patient, when the packing updating works I'll fix all the packages.

Dion

On Wednesday, January 25, 2012, Jason O'Neil <
reply@reply.github.com>
wrote:

**Comment by jasononeil** [comment]
Ah I remember reading that, no worries.  In the mean time, would I have
better luck getting the latest repos from github?

On Wed, Jan 25, 2012 at 3:16 PM, Dion Whitehead Amago <
reply@reply.github.com

**Comment by dionjwa** [comment]
Yes, use github. It's in active development, but reasonably stable, and lots of bugs are fixed.

Dion

**Comment by dionjwa** [comment]
This dependency is now a submodule and up to date.

**Comment by jasononeil** [comment]
Thank you!

On Thu, Apr 5, 2012 at 2:24 PM, Dion Whitehead Amago <
reply@reply.github.com
